name: Hello World PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World! This is a check that runs on pull requests."
