name: Validate Work Item in PR

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  check-work-item:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout Workflows Repository
      uses: actions/checkout@v3
      with:
        repository: optimove-tech/workflows
        path: org-workflows
        ref: 'check-another-validation'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Check for Work Item in PR Title or Description
      id: ifLinked
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADO_PAT: ${{ secrets.ADO_PAT }}
        ADO_ORG: 'mobius'
        ADO_PROJECT: 'Backstage'
      run: |
        PULL_REQUEST=$(gh api ${{ github.event.pull_request.url }})

        PR_TITLE=$(echo $PULL_REQUEST | jq --raw-output .title)
        PR_BODY=$(echo $PULL_REQUEST | jq --raw-output .body)

        echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
        echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV

        #python3 org-workflows/.github/workflows/validate-ado-wi/validate-pattern.py -checklist "['$PR_BODY', 'PR_TITLE']"
        python3 org-workflows/.github/workflows/validate-ado-wi/validate-wi-exists.py -checklist "['$PR_BODY', 'PR_TITLE']" -organization '$ADO_ORG' -project '$ADO_PROJECT' -pat '$ADO_PAT'

    - name: Ping PR Author to link Work Item
      if: ${{ failure() && steps.ifLinked.conclusion == 'failure' }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 Hey @${{ github.event.pull_request.user.login }},
            
            ❗️ Work Item link check failed: There is no Work Item linked to this PR. 
            
            🧩 Please add the Work Item ID to the PR title or description using the "Edit" option in the format below:
            AB#XXXXX - replace X with a valid Work Item ID.
            
            🟢 After that, please use "Re-run jobs" in PR check or proceed with "Close pull request" and "Reopen pull request" options below to restart the validation.`
          })

    - name: Ping PR Author to verify Work Item ID
      if: ${{ failure() && steps.ifExists.conclusion == 'failure' }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 Hey @${{ github.event.pull_request.user.login }},
            
            ❗️ Work Item link check failed: The specified Work Item ID could not be found.
            
            🔎 Make sure the Work Item ID exists in the PR title or description, and correct it using the "Edit" option in the format below:
            AB#XXXXX - replace X with a valid Work Item ID.
            
            🟢 Once corrected, please use "Re-run jobs" in PR check or proceed with "Close pull request" and "Reopen pull request" options below to restart the validation.`
          })