name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_configuration_repo: workflows
          pass_on_octokit_error: false
          github_configuration_ref: check-another-validation
          github_configuration_path: pr-title-checker-config.json #(optional. defaults to .github/pr-title-checker-config.json)