name: Validate Work Item in PR

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  check-work-item:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Get PR title & body
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PULL_REQUEST=$(gh api ${{ github.event.pull_request.url }})

        PR_TITLE=$(echo $PULL_REQUEST | jq --raw-output .title)
        PR_BODY=$(echo $PULL_REQUEST | jq --raw-output .body)

        echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
        echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV

        
    - name: Check for Work Item in PR Title or Description
      id: ifLinked
      shell: python
      run: |
        import re
        import sys
        import os
        
        PR_BODY = os.environ['PR_BODY']
        PR_TITLE = os.environ['PR_TITLE']

        def check_for_pattern(strings):
            pattern = r"AB#\d+"
            check_confirmed = [string for string in strings if re.search(pattern, string)]
            return check_confirmed
            
        checklist = [PR_BODY, PR_TITLE]
        check_confirmed = check_for_pattern(checklist)
        
        if check_confirmed:
            print("Found linked working item:", check_confirmed)
        else:
            print("No linked working item found.")
            sys.exit(1)
       
    - name: Check Work Item in PR Title or Description is exist
      id: ifExists
      shell: python
      env:
        ADO_PAT: ${{ secrets.ADO_PAT }}
        ADO_ORG: 'mobius'
        ADO_PROJECT: 'Backstage'
      run: |
        import re
        import requests
        import sys 
        import os

        PR_BODY = os.environ['PR_BODY']
        PR_TITLE = os.environ['PR_TITLE']

        org = os.environ['ADO_ORG']
        project = os.environ['ADO_PROJECT']
        pat = os.environ['ADO_PAT']
        
        def extract_and_verify_work_items(checklist, organization, project, pat):
            pattern = r"AB#(\d+)"
            headers = {
                'Content-Type': 'application/json'
            }
        
            for string in checklist:
                for match in re.finditer(pattern, string):
                    work_item_id = match.group(1)
                    url = f"https://dev.azure.com/{organization}/{project}/_apis/wit/workitems/{work_item_id}?api-version=6.0"
                    print(url)
                    response  = requests.get(url, headers=headers, auth=('', pat))
                    if response.status_code == 200:
                        print(f"Work item AB#{work_item_id} exists.")
                    else:
                        print(f"Work item AB#{work_item_id} does not exist or access denied.")
                        print(response.status_code)
                        sys.exit(1)
        
        
        checklist = [PR_BODY, PR_TITLE]
        extract_and_verify_work_items(checklist, org, project, pat)

    - name: Ping PR Author to link Work Item
      if: ${{ failure() && steps.ifLinked.conclusion == 'failure' }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 Hey @${{ github.event.pull_request.user.login }},
            
            ❗️ Work Item link check failed: There is no Work Item linked to this PR. 
            
            🧩 Please add the Work Item ID to the PR title or description using the "Edit" option in the format below:
            AB#XXXXX - replace X with a valid Work Item ID.
            
            🟢 After that, please use "Re-run jobs" in PR check or proceed with "Close pull request" and "Reopen pull request" options below to restart the validation.`
          })

    - name: Ping PR Author to verify Work Item ID
      if: ${{ failure() && steps.ifExists.conclusion == 'failure' }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 Hey @${{ github.event.pull_request.user.login }},
            
            ❗️ Work Item link check failed: The specified Work Item ID could not be found.
            
            🔎 Make sure the Work Item ID exists in the PR title or description, and correct it using the "Edit" option in the format below:
            AB#XXXXX - replace X with a valid Work Item ID.
            
            🟢 Once corrected, please use "Re-run jobs" in PR check or proceed with "Close pull request" and "Reopen pull request" options below to restart the validation.`
          })
