name: Validate Work Item in PR

on:
  workflow_dispatch:


jobs:
  check-work-item:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout Workflows Repository
      uses: actions/checkout@v3
      with:
        repository: optimove-tech/workflows
        path: org-workflows
        ref: 'main'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Get PR title & body
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PULL_REQUEST=$(gh api ${{ github.event.pull_request.url }})

        PR_TITLE=$(echo $PULL_REQUEST | jq --raw-output .title | tr '\n' ' ' | tr -d "[]'")
        PR_BODY=$(echo $PULL_REQUEST | jq --raw-output .body | tr '\n' ' ' | tr -d "[]'")

        echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
        echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV

    - name: Check for Work Item in PR Title or Description
      id: ifLinked
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "PR Title: $PR_TITLE"
        echo "PR Body: $PR_BODY"
        CHECKLIST=$(jq -nc --arg body "$PR_BODY" --arg title "$PR_TITLE" '[$body, $title]')
        python3 org-workflows/.github/workflows/validate-ado-wi/validate-pattern.py -checklist "$CHECKLIST"

    - name: Check Work Item in PR Title or Description is exist
      id: ifExists
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADO_PAT: ${{ secrets.ADO_PAT }}
      run: |
        echo "PR Title: $PR_TITLE"
        echo "PR Body: $PR_BODY"
        CHECKLIST=$(jq -nc --arg body "$PR_BODY" --arg title "$PR_TITLE" '[$body, $title]')
        python3 org-workflows/.github/workflows/validate-ado-wi/validate-wi-exists.py -checklist "$CHECKLIST"  -organization 'mobius' -project 'Backstage'

    - name: Ping PR Author to link Work Item
      if: ${{ failure() && steps.ifLinked.conclusion == 'failure' }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 Hey @${{ github.event.pull_request.user.login }},
            
            ❗️ Work Item link check failed: There is no Work Item linked to this PR. 
            
            🧩 Please add the Work Item ID to the PR title or description using the "Edit" option in the format below:
            AB#XXXXX - replace X with a valid Work Item ID.
            
            🟢 Once added, please use "Re-run jobs" in PR check or proceed with "Close pull request" and "Reopen pull request" options below to restart the validation.`
          })

    - name: Ping PR Author to verify Work Item ID
      if: ${{ failure() && steps.ifExists.conclusion == 'failure' }}
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 Hey @${{ github.event.pull_request.user.login }},
            
            ❗️ Work Item link check failed: The specified Work Item ID could not be found.
            
            🔎 Make sure the Work Item ID exists in the PR title or description, and correct it using the "Edit" option in the format below:
            AB#XXXXX - replace X with a valid Work Item ID.
            
            🟢 Once corrected, please use "Re-run jobs" in PR check or proceed with "Close pull request" and "Reopen pull request" options below to restart the validation.`
          })
